# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c27e042269833eeb69c700337117f2ef"
name = "form_design"
application_url = "https://formdesign.androgamesinfotech.tech"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[[webhooks.subscriptions]]
uri = "https://form-design-opal.vercel.app/webhooks/app/scopes_update"
topics = ["app/scopes_update"]

[[webhooks.subscriptions]]
uri = "https://form-design-opal.vercel.app/webhooks/app/uninstalled"
topics = ["app/uninstalled"]

[[webhooks.subscriptions]]
uri = "https://formdesign.androgamesinfotech.tech/webhooks"
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products,write_online_store_pages,read_online_store_pages"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://formdesign.androgamesinfotech.tech/auth/callback" ]

[app_proxy]
url = "https://formdesign.androgamesinfotech.tech/api/storefront"
subpath = "form-design"
prefix = "apps"
